// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TarefasWebApi;
using TarefasWebApi.Models.Enums;

namespace TarefasWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220903181355_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("TarefasWebApi.Models.Tarefa", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Tarefas");

                    b.HasData(
                        new
                        {
                            Codigo = 1,
                            Descricao = "Tomar café da manhã",
                            Status = Status.Pendente
                        },
                        new
                        {
                            Codigo = 2,
                            Descricao = "Levar as crianças para a escola",
                            Status = Status.Pendente
                        },
                        new
                        {
                            Codigo = 3,
                            Descricao = "Ir ao trabalho",
                            Status = Status.Pendente
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
